set_property IOSTANDARD LVCMOS33 [get_ports led]
set_property IOSTANDARD LVCMOS33 [get_ports switch_a]
set_property IOSTANDARD LVCMOS33 [get_ports switch_b]
set_property PACKAGE_PIN V16 [get_ports switch_a]
set_property PACKAGE_PIN V17 [get_ports switch_b]
set_property PACKAGE_PIN U16 [get_ports led]
